### PR TITLE
Added JavaScript Cheat Sheet

### LINKED ISSUE #93: JavaScript Cheat Sheet
I will add a basic JavaScript cheat sheet required for web development

### PR DESCRIPTION
**Pull request by Villain45**
fixes #93 
Cheat Sheet of basic Java Script is added

### CODE REVIEW

**Review by crescentpartha — CHANGES_REQUESTED** [review]
You are most welcome. LTMG!
Some modifications:
- Please, give the `tabular format` like [git-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/git-cheatsheet.md), It will be better to visualize and understand the whole cheatsheet. 
- Modify file name like `JavaScript.md` to `javascript-cheatsheet.md`
- Add your `javascript-cheatsheet.md` file in `README.md` file.

Thanks, @Villain45

**Comment by crescentpartha** [comment]
This is the `Tabular format`. - @Villain45 

## String Methods

| Methods | Descriptions |
| ---------- | -------------  |
| charAt() | Returns a character at a specified position inside a string |
| charCodeAt() | Gives you the unicode of character at that position |

**Comment by Villain45** [comment]
@crescentpartha checkout now

**Review by crescentpartha — APPROVED** [review]
You didn't follow the cheatsheet template based on `git-cheatsheet.md`. 
In contrast, I approved it. Need to modify it next time.

**Pull request merged**
