### PR TITLE
Create Sklearn-cheatsheet.md

### PR DESCRIPTION
**Pull request by Swastik3025**
### Checklist:
- [x] Read our [contributing guidelines](../docs/CONTRIBUTING.md).
- [x] Search for duplicates.
- [x] Used an informative name for this pull request.

### Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Swastik3025** [comment]
Please comment if there is any issue with my repo.

**Review by crescentpartha — CHANGES_REQUESTED** [review]
Everything looks to me good! But need some structural modifications.

Please read our [contributing guidelines](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md) and follow the [new CheatSheet Instructions](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md#introduceadd-a-new-cheatsheet) and [the template](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/docs/CheatSheet-Template.md) for a new cheatsheet.

**Review by Swastik3025 — COMMENTED** [review]
added a tabular description and table of contents

**Review by crescentpartha — APPROVED** [review]
Approved your changes.

**Pull request merged**
