### PR TITLE
Sql cheatsheet part 2

### PR DESCRIPTION
**Pull request by ritwikdalmia**

### CODE REVIEW

**Review by crescentpartha — CHANGES_REQUESTED** [review]
What you did in this PR, I don't understand. 
Please, keep your fork branch `up-to-date` first. After that, create a `pull request`.

Your branch is [4 commits ahead](https://github.com/ritwikdalmia/CheatSheets-for-Developers/compare/crescentpartha:CheatSheets-for-Developers:main...sql-cheatsheet-part-2), [61 commits behind](https://github.com/ritwikdalmia/CheatSheets-for-Developers/compare/sql-cheatsheet-part-2...crescentpartha:CheatSheets-for-Developers:main) crescentpartha:main.

**Comment by crescentpartha** [comment]
`Sql cheatsheet part 2` has already been added with `Sql cheatsheet part 3`. Please, check the [sql-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/sql-cheatsheets.md) file. @ritwikdalmia

**Comment by ritwikdalmia** [comment]
earlier my merge  request 125 didnt able to merge so i re created the pull
request(part 2)
but the pull request 127 has been merged (part 3)

**Comment by ritwikdalmia** [comment]
ok i will check that

**Pull request closed without merging**
