### PR TITLE
Sql cheatsheets part 3

### PR DESCRIPTION
**Pull request by ritwikdalmia**

### CODE REVIEW

**Comment by ritwikdalmia** [comment]
can u please add the tag hacktoberfest-accepted

**Review by crescentpartha — CHANGES_REQUESTED** [review]
Please, `Modify your code` according to [original sql-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/sql-cheatsheets.md#table-of-contents) file. I merged your `sql-cheatsheet-part-1` and then modified some structural changes. Please, follow the current structure in your next pull requests.
Thank you, @ritwikdalmia

**Comment by crescentpartha** [comment]
> can u please add the tag hacktoberfest-accepted

It will be added when your pull request will be successfully merged with the original repo.

**Comment by crescentpartha** [comment]
Please, `delete some lines of code` which is `already merged` in the `sql-cheatsheet-part1` and `sql-cheatsheet-part2`. After that, follow the [original sql-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/sql-cheatsheets.md#table-of-contents) file.

**Comment by crescentpartha** [comment]
Please, keep your branch up-to-date, then added the part-3 section and add one more commit. that's it.

**Comment by ritwikdalmia** [comment]
> Please, keep your branch up-to-date, then added the part-3 section and add one more commit. that's it.

updated and modified

**Review by crescentpartha — APPROVED** [review]
Approved your changes.

**Pull request merged**
