### PR TITLE
Cmd

### PR DESCRIPTION
**Pull request by ArchitKumar-13**
removed line number 46

### CODE REVIEW

**Comment by ArchitKumar-13** [comment]
hey @crescentpartha, actually this is my first time contributing so that's why I'm a bit nervous. Do let me know if you want me to add rename command (as I have removed the command and updated the .md file)

**Comment by ArchitKumar-13** [comment]
Can you tell if my updated content is merged or not, I cannot able to see it

**Review by crescentpartha — APPROVED** [review]
Approved your changes

**Review by crescentpartha — APPROVED** [review]
Approved your changes

**Pull request merged**
