### PR TITLE
Sql cheatsheets part 2

### PR DESCRIPTION
**Pull request by ritwikdalmia**
### Checklist:
- [x] Read our [contributing guidelines](../docs/CONTRIBUTING.md).
- [ ] Search for duplicates.
- [ ] Used an informative name for this pull request.

### Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by crescentpartha — CHANGES_REQUESTED** [review]
Please, `Modify your code` according to [original sql-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/sql-cheatsheets.md#table-of-contents) file. I merged your `sql-cheatsheet-part-1` and then modified some structural changes. Please, follow the current structure in your next pull requests.
Thank you, @ritwikdalmia

**Comment by ritwikdalmia** [comment]
hello sir this is a updated SQL cheatsheet please update this also

**Comment by crescentpartha** [comment]
Please, `delete some lines of code` which is `already merged` in the `sql-cheatsheet-part2`. After that, follow the [original sql-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/sql-cheatsheets.md#table-of-contents) file.

**Comment by ritwikdalmia** [comment]
why to delete the some of the lines that are already written on sql part 1
i didnt get it can you please ellaborate

**Comment by crescentpartha** [comment]
Please, keep your branch up-to-date, then added the part-2 section. that's it.

**Comment by ritwikdalmia** [comment]
> Please, keep your branch up-to-date, then added the part-2 section. that's it.

updated and modified

**Review by crescentpartha — APPROVED** [review]
Approved.

**Review by crescentpartha — CHANGES_REQUESTED** [review]
You changed the original file, that's why GitHub doesn't give access to merge your pull request.

**Comment by crescentpartha** [comment]
conflict
Please, create another `pull request`. The resolved conflict option is `disabled`, so can't make any changes to resolve the conflict. Please, make sure your fork branch is up-to-date before contributions. I closed this pull request.

**Comment by ritwikdalmia** [comment]
ohk sir got it i have created the new pull request

**Pull request closed without merging**
