### PR TITLE
Now I have updated the changes and added some windows keyboard shortcuts.

### PR DESCRIPTION
**Pull request by amanaggarwal06**
### Checklist:
- [x] Read our [contributing guidelines](../docs/CONTRIBUTING.md).
- [x] Search for duplicates.
- [x] Used an informative name for this pull request.

### Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by amanaggarwal06** [comment]
Now I made one PR before this and asked to make some changes. As I'm new to open source and didn't know much about how to update the previous PR, that's why I have created the new PR.

**Comment by crescentpartha** [comment]
> Now I made one PR before this and asked to make some changes. As I'm new to open source and didn't know much about how to update the previous PR, that's why I have created the new PR.

It's very easy. Just modify the code according to the review and add another commit. This commit will automatically add to the pull request section. Please, try next time.

**Comment by amanaggarwal06** [comment]
> > Now I made one PR before this and asked to make some changes. As I'm new to open source and didn't know much about how to update the previous PR, that's why I have created the new PR.
> 
> It's very easy. Just modify the code according to the review and add another commit. This commit will automatically add to the pull request section. Please, try next time.

Thanks for telling me. I'll do that next time.

**Review by crescentpartha — APPROVED** [review]
Approved your changes.

**Pull request merged**
