### PR TITLE
Update java-cheatsheet.md

### PR DESCRIPTION
**Pull request by silky-modi22**
### Checklist:
- [x] Read our [contributing guidelines](../docs/CONTRIBUTING.md).
- [ ] Search for duplicates.
- [ ] Used an informative name for this pull request.

### Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by silky-modi22** [comment]
What to do now, to merge my pr and how to review it

**Comment by silky-modi22** [comment]
Is any other changes required in my contribution file please let me know
and if not required please merge it

**Review by crescentpartha — APPROVED** [review]
Approved your changes.

**Comment by silky-modi22** [comment]
Thank you

**Pull request merged**
